import { createServer } from "node:http";
import { readFileSync } from "node:fs";
const PORT=Number(process.env.PORT||7860);
const INDEX=readFileSync(new URL("./public/index.html",import.meta.url));
const decode=s=>(s||"").replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g,"$1").replace(/&amp;/g,"&").replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/&quot;/g,'"').replace(/&#39;/g,"'");
const clean=s=>decode(s).replace(/<[^>]*>/g," ").replace(/\s+/g," ").trim();
function tag(xml,name){const m=xml.match(new RegExp(`<${name}(?:\\s[^>]*)?>([\\s\\S]*?)<\\/${name}>`,"i"));return m?clean(m[1]):""}
function parse(xml){return [...xml.matchAll(/<item>([\s\S]*?)<\/item>/gi)].map((m,i)=>({id:String(i+1),title:tag(m[1],"title"),link:tag(m[1],"link"),publishedAt:tag(m[1],"pubDate"),description:tag(m[1],"description"),source:tag(m[1],"source")||"Google News"})).filter(x=>x.title&&x.link)}
const STOP=new Set("the a an and or but for with from into over after before about this that these those is are was were be been being to of in on at by as it its their his her they he she you your our new says said amid how why what when where who australia australian latest live update updates".split(/\s+/));
const words=t=>(t||"").toLowerCase().replace(/[^a-z0-9\u4e00-\u9fff\s-]/g," ").split(/\s+/).filter(w=>w.length>2&&!STOP.has(w));
function brief(topic,articles){const c=new Map();articles.forEach(a=>words(a.title+" "+a.description).forEach(w=>c.set(w,(c.get(w)||0)+1)));const keys=[...c.entries()].sort((a,b)=>b[1]-a[1]).slice(0,8).map(([word,count])=>({word,count}));const ranked=articles.map((a,i)=>({...a,score:words(a.title).reduce((s,w)=>s+(c.get(w)||0),0)-i*.15})).sort((a,b)=>b.score-a.score);const themes=keys.slice(0,5).map(k=>k.word);return{topic,generatedAt:new Date().toISOString(),count:articles.length,topStory:ranked[0]||null,themes,keywords:keys,watch:themes.length?`接下来重点观察：${themes.slice(0,3).join("、")}相关报道是否持续增加，以及不同媒体是否出现一致方向。`:`继续关注 ${topic} 的后续报道。`,headlines:ranked.slice(0,12)}}
async function fetchNews(topic,count){const u=`https://news.google.com/rss/search?q=${encodeURIComponent(topic)}&hl=en-AU&gl=AU&ceid=AU:en`;const r=await fetch(u,{headers:{"user-agent":"Mozilla/5.0 FreeNewsSummarizer/1.0"},signal:AbortSignal.timeout(12000)});if(!r.ok)throw new Error(`News feed returned ${r.status}`);return parse(await r.text()).slice(0,count)}
function send(res,status,body){res.writeHead(status,{"content-type":"application/json; charset=utf-8","cache-control":"no-store","access-control-allow-origin":"*"});res.end(JSON.stringify(body))}
createServer(async(req,res)=>{try{const u=new URL(req.url||"/",`http://${req.headers.host||"localhost"}`);if(u.pathname==="/"||u.pathname==="/index.html"){res.writeHead(200,{"content-type":"text/html; charset=utf-8"});return res.end(INDEX)}if(u.pathname==="/health")return send(res,200,{status:"ok"});if(u.pathname==="/api/news"){const topic=(u.searchParams.get("topic")||"Australia financial markets").trim().slice(0,120);const count=Math.min(25,Math.max(3,Number(u.searchParams.get("count")||12)));const articles=await fetchNews(topic,count);return send(res,200,{articles,brief:brief(topic,articles)})}send(res,404,{error:"Not found"})}catch(e){console.error(e);send(res,500,{error:e.message||"Unable to fetch news"})}}).listen(PORT,"0.0.0.0",()=>console.log(`Listening on ${PORT}`));
